version: '2'
services:
  postgresdata:
    image: "postgres"
    container_name: postgresdata
    volumes:
      - /mnt/data:/var/lib/postgresql/data
    command: /bin/true
    
  postgresdb:
    image: "harshals/mypostgres:1.4"
    container_name: postgresdb
    volumes_from:
      - postgresdata
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
  pgwriter:
    image: "harshals/postgreswriter:1.3"
    container_name: "pgwriter"
    links:
      - "postgresdb:postgres"
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=mypguser
      - POSTGRES_DB=flktstdb
      - POSTGRES_TABLE=flockertab
      - POSTGRES_HOST=postgres
  web:
    restart: always
    container_name: "web"
    image: "harshals/web:1.0"
    expose:
      - "8000"
    links:
      - "postgresdb:postgres"
    depends_on:
      - pgwriter
    volumes:
      - /vagrant/web/static:/usr/src/app/static
    env_file: ./config/.env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    container_name: "ngnix"
    restart: always
    image: "harshals/nginx:1.0"
    ports:
      - "80:80"
    volumes:
      - /vagrant/web/static:/www/static
    volumes_from:
      - web
    links:
      - web:web


